### PR TITLE
Fixes unable to find joomla binary

### PR DESCRIPTION
**Pull request by fintanmm**
Hi all,

This PR sets the composer home directory, then creates a symlink to joomla tools. The test checks that the symlink is in place and joomla tools has the correct permissions. 

Regards,
Fintan

### CODE REVIEW

**Review by aboe76 — APPROVED** [review]
looks good

**Comment by fintanmm** [comment]
Oops forgot I had this PR open.

**Comment by fintanmm** [comment]
@aboe76 Do you want me to break this up?

**Comment by fintanmm** [comment]
@aboe76, can I go ahead and merge this?

**Comment by aboe76** [comment]
@fintanmm merged it.

**Pull request merged**
